Add docs index and fix typo in contribute
canonical/pollen-operator pull request #25
Opened 2023-09-01 15:08 UTC by gtrkiller

Follow up to #24 to fix what is needed.

2023-09-01 15:23 UTC, arturo-seijas approved these changes
LGTM

2023-09-04 05:14 UTC, jdkandersson commented
Is this missing the description defined in ISD062?

2023-09-04 14:49 UTC, jdkandersson commented on docs/index.md
> +# Navigation
Should this use the contents index format? https://github.com/canonical/upload-charm-docs#contents-index

2023-09-04 20:16 UTC, amandahla commented on .github/pull_request_template.md
> +Thank you for your interest in and contributing to Synapse Operator!
Synapse? ;-)

2023-09-05 06:37 UTC, jdkandersson requested changes
Please ensure this PR complies with ISD062

2023-09-05 06:44 UTC, merkata commented
> Please ensure this PR complies with ISD062

@gtrkiller you can copy a template from [here](https://github.com/canonical/synapse-operator/pull/30) for instance and make use of it until the template is replicated across all our repos. Please note that if a checkbox is not applicable, you should check it and not leave it empty. Leaving it empty leaves the impression it is not done yet, marking it signals it is either done or not applicable for this PR. Thanks!

PS add a label ;)

2023-09-05 20:10 UTC, amandahla submitted a review, later dismissed
LGTM

2023-09-06 01:43 UTC, nrobinaubertin approved these changes

2023-09-07 15:09 UTC, jdkandersson reviewed
There are still some earlier comments that were marked as resolved but don't seem to be resolved yet, I have un-resolved them, please take a look

2023-09-07 15:10 UTC, jdkandersson approved these changes
Marking as approved to remove the requested changes tag, please address the earlier comment

2023-09-08 06:30 UTC, jdkandersson approved these changes

2023-09-12 08:02 UTC, arturo-seijas approved these changes
LGTM

2023-09-12 12:31 UTC, arturo-seijas approved these changes

2023-09-12 12:45 UTC, merged